import Head from 'next/head'
import Image from 'next/image'
import React, {useState} from 'react'
import Header from '@/components/header'
import Form from '@/components/form'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Tasklist from '@/components/tasklist'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [input, setInput] = useState("");
  const [todos, setTodos] = useState([]);
  const [editTodo, setEditTodo] =useState(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.Container}>
      <Header/>
        <div className={styles.space}> 
     
      <div className={styles.white}>
      <Form
      input={input}
      setInput={setInput}
      todos={todos}
      setTodos={setTodos}
      editTodo={editTodo}
      setEditTodo={setEditTodo}
      />
      </div>
      <div className={styles.formcontainer}>
      <Tasklist 
      setEditTodo={setEditTodo}
      todos={todos} setTodos={setTodos}
      />
      </div>
      </div>
      </div>
      </main>
    </>
  )
}
